### PR TITLE
[WIP] Let .travis test Symfony 2.8 and 3.0

### PR DESCRIPTION
**Pull request by rvanlaak**
also see https://docs.google.com/spreadsheets/d/1GOxJ2lNpLxN12YyZ87Bhsxb0iLAQ7e4UDZbJSly8Sy8/edit

### CODE REVIEW

**Comment by Rvanlaak** [comment]
[DoctrineMongoDBBundle/blob/master/composer.json](https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/composer.json) is pinned at `symfony/framework-bundle:~2.1` so Composer won't be able to resolve the dev dependencies for `3.0`.

**Comment by WouterJ** [comment]
@Rvanlaak yeah, so you first have to fix Symfony 3 support for that bundle. As a little hack, you can use `SYMFONY_VERSION='3.0.*@dev as 2.8.x-dev'` for testing this bundle

**Comment by Rvanlaak** [comment]
Let's see or the composer alias does the trick ;) Maybe that's something you can add as a tip to the spreadsheet, because other bundles will also have this problem.

**Comment by Rvanlaak** [comment]
Travis build on `3.0` still fails, the `2.8.x-dev` alias is in the list of options but isn't recognized properly? 

https://travis-ci.org/lexik/LexikFormFilterBundle/jobs/90489264#L120

**Comment by WouterJ** [comment]
Hmm, can you please try using `3.0.x-dev as 2.8`? This is used by the JaviereguiluzEasyAdminBundle: https://github.com/javiereguiluz/EasyAdminBundle/blob/master/.travis.yml#L37 (the alias syntax always confuses me...)

**Comment by rvanlaak** [comment]
That didn't seem to do the trick, but it actually is the `mongo-odm-bundle` that can't be resolved, so don't think the alias will solve this.

**Pull request closed without merging**
