### PR TITLE
Handle timezones in a correct way.

### PR DESCRIPTION
**Pull request by phjedi**
Hi guys.
It looks like you omitted Symfony2 form options like 'model_timezone' and 'view_timezone' using the next chunk of code:

```php
    protected function convertToSqlDate($date, $isMax = false)
    {
        if (! $date instanceof \DateTime) {
            return;
        }

        if ($isMax) {
            $date->setTime(23, 59, 59);
        } else {
            $date->setTime(0, 0, 0);
        }

        return $this->expr()->literal($date->format(self::SQL_DATE_TIME));
    }
```

We kindly ask you to replace it with something like this one:

```php
    protected function convertToSqlDate($date, $isMax = false)
    {
        if (! $date instanceof \DateTime) {
            return;
        }

        if ($isMax) {
            $date->modify('+1 day -1 second');
        }

        return $this->expr()->literal($date->format(self::SQL_DATE_TIME));
    }
```

It should handle timezones in a correct way.

### CODE REVIEW

**Comment by phjedi** [comment]
ping @cedric-g

**Comment by Rvanlaak** [comment]
Your change does not handle the `else` case anymore.

**Comment by phjedi** [comment]
It's not needed. 

For example, we have form with date range and different timezones in view and data.

```php
        $builder->add('date_range', 'filter_date_range', [
            'left_date_options' => [
                'model_timezone'    => 'UTC',
                'view_timezone'     => 'Asia/Karachi',
            ],
            'right_date_options' => [
                'model_timezone'    => 'UTC',
                'view_timezone'     => 'Asia/Karachi',
            ],
        ]);
```

User input: `2015-10-01` and `2015-10-16` (timezone Asia/Karachi)
After submit we have: `2015-09-30 19:00` and `2015-10-15 19:00` (timezone UTC)

And after filter: `2015-09-30 00:00:00` and `2015-10-15 23:59:59` - **this is wrong**

True way: do not change `left_date` and add 1 day to `right_way` to include this date in query.

**Comment by Rvanlaak** [comment]
:+1: can you also write a test for that, so we're sure this properly works on all supported PHP versions?

**Comment by phjedi** [comment]
Added. This is what you need?

**Comment by cedric-g** [comment]
Thx :smiley:

**Pull request merged**
