### PR TITLE
Add KNP Paginator example to docs fixes #144

### LINKED ISSUE #144: Too few parameters using filter_entity with knp_paginator
I coupled this bundle to the `knp_paginator`. I added a `fitler_entity` and then passed the `query` as described in the docs:
https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/working-with-the-bundle.md#i-simple-example

```php
$query = $filterBuilder->getDql();
```

This will throw: **Too few parameters: the query defines 1 parameters but you only bound 0**.

As @cedric-g correctly stated in https://github.com/lexik/LexikFormFilterBundle/issues/89 the `getDql()` method only returns the DQL string without the parameters.

Instead I had to use:
```php
$query = $filterBuilder->getQuery();
```

Maybe we could add an example to the docs?

### PR DESCRIPTION
**Pull request by webdevilopers**
Thoughts, @cedric-g ?

As discussed in https://github.com/lexik/LexikFormFilterBundle/issues/144#issuecomment-92935350.

### CODE REVIEW

**Comment by cedric-g** [comment]
Thx :)

**Comment by webdevilopers** [comment]
I based the example on the existing ones in the docs e.g.:
https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/working-with-the-bundle.md#i-simple-example

Are you planning some global improvement of the docs @cedric-g in the near future?

**Comment by cedric-g** [comment]
I think I will check every Lexik bundle when SF 2.7 will be released as stable.

**Comment by webdevilopers** [comment]
Great @cedric-g !

**Pull request merged**
