### PR TITLE
Allow entities with public `id` attribute

### PR DESCRIPTION
**Pull request by sroze**
This PR allow to use an entity filter with entities that have their ID behind a public attribute instead of a getter.

We could have used PropertyAccessor component but I think that's a two much overhead here.

### CODE REVIEW

**Comment by Rvanlaak** [comment]
How does this work when the identifier isn't an id but a string for example? I know the old code also contained a hardcoded `getId` check, so this solution already seems better. 

Will it also work with [composite keys](http://doctrine-orm.readthedocs.org/en/latest/tutorials/composite-primary-keys.html)? Or should `getId()` return an array with the composite key in that case?

**Comment by sroze** [comment]
It's working with a string identifier, but won't for composite keys, even if `getId` return an array. 

If you need support of composite keys, we'll need to change the way we're adding conditions [here](https://github.com/lexik/LexikFormFilterBundle/pull/138/files#diff-5af2eb44ed2cc52bcc42d7c26096db1dR82) and [here](https://github.com/lexik/LexikFormFilterBundle/pull/138/files#diff-5af2eb44ed2cc52bcc42d7c26096db1dR89) as we'll need to add a condition per part of the composite key.

**Comment by Rvanlaak** [comment]
What you're saying was exactly what I've noticed. Not just a case of replacing
```php
if (count($ids) > 0) {
```
by
```php
foreach ($ids as $id) {
```
?

At the moment we're not using composite keys, so everything works fine for me. If it would be this easy, this could be a quick win (?)

**Comment by sroze** [comment]
Well, in fact you're right: the only need is that the `getId` method returns an associated array as in [this](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/composite-primary-keys.html#composite-and-foreign-keys-as-primary-key) Doctrine example:
```php
$dql = "SELECT c FROM VehicleCatalogue\Model\Car c WHERE c.id = ?1";
$audi = $em->createQuery($dql)
           ->setParameter(1, array("name" => "Audi A8", "year" => 2010))
           ->getSingleResult();
```

So no need to change, it's already a quick win :)

**Pull request merged**
