### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by danut007ro**

### CODE REVIEW

**Comment by spike31** [comment]
Hi @danut007ro ,

You fix tests, but I don't understand when tests were broken?

**Comment by danut007ro** [comment]
Hello, they were failing in this PR, and also on another of mine, #334

I guess it's failing from another updated library, for building mongodb json request

**Comment by spike31** [comment]
Ok, I will merge your PR, that a strange situation! :)

**Comment by danut007ro** [comment]
Thanks

**Pull request merged**
