### PR TITLE
Update ci.yml with Symfony 6.2, 6.3

### PR DESCRIPTION
**Pull request by spike31**

### CODE REVIEW

**Comment by spike31** [comment]
@fabpot any ideas with errors for 6.3?

**Comment by nicolas-grekas** [comment]
I'd say the container is freed before the end of the test case. You need to hold a reference to it until the end of the tests by putting it in a variable.

**Comment by spike31** [comment]
Ok I will continu to search, but why it's work with 6.2 and not with 6.3?

https://github.com/lexik/LexikFormFilterBundle/blob/master/Tests/TestCase.php#L133-L188

**Comment by nicolas-grekas** [comment]
This looks like a side-effect of https://github.com/symfony/symfony/pull/48469

**Comment by spike31** [comment]
Ok Thank you @nicolas-grekas I have hold a static reference of the container and it's ok. Not easy with WeakReference I suppose

**Pull request merged**
