### PR TITLE
update symfony way

### PR DESCRIPTION
**Pull request by cordoval**
@sstok perhaps you can help me keeping BC, but i think this should get rid of the annoying things in yellow

### CODE REVIEW

**Comment by Rvanlaak** [comment]
:+1: what a coincidence, also have been busy with this today. A new release would be great, so I can use it in our live release later this week.

@cordoval can you try to also implement the `choice_translation_domain` for the entity type? So we can set it to `false` in order to don't translate those.

**Comment by sstok** [comment]
Hhmm. Its possible bump the major version for Symfony 2.7 compatibility and keep an older branch for Symfony 2.3. Or you can detect if the Interface is used or not, but thats only for compatibility and will not prevent the deprecation messages (IIRC).

**Comment by cordoval** [comment]
@Rvanlaak do you have an example on how to implement the choice_translation_domain for those types? or you want it only for the entity type? i am a bit unclear on that.

**Comment by Rvanlaak** [comment]
Well, I don't want the Entity labels to be translated, because they already use an Entity's property as the label. That's why `2.7` has the `choice_translation_domain`, but the current implementation of the `filter_entity` does not seem to support it.

**Comment by cedric-g** [comment]
Hi, I prefer drop support of old version, so the `3.0.8` tag is the last one compatible with Symfony 2.3.

**Pull request merged**
